# Generated by Django 6.0.1 on 2026-02-17 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('date', 'start_time', 'end_time'), name='unique_booking_slot'),
        ),
    ]
